### ISSUE TITLE
support for .elapsed ()

### ISSUE THREAD

**Issue by emahuni** [rommelsantor/Timeout#20]
The remaining function is a God-sent, I think another one is missing, which I have been trying to use: 
```js
timeout.set('huga', ()=>console.log('huga done!'), 5000);
// ... later on just like remaining()...
timeout.elapsed('huga')
// => 3384
```

this is just the opposite of remaining

**Comment by rommelsantor** [comment]
Hi @emahuni- Thanks for the suggestions.

Can you please help me understand example use cases? In what context are you trying to do this?

Would this be the elapsed time from the time it was last set or the time elapsed since the callback fired?

**Comment by emahuni** [comment]
It's the exact opposite of remaining. So if the timeout was 2000 and we get 1500 when we do remaining (), then elapsed would be 500.

This lib is used to keep track of a status lifetime so we need to just display the elapsed without calculating the difference between remaining and the initial timeout value passed, which we may not have access to.

**Comment by rommelsantor** [comment]
Thank you for the clarification.

It's not actually "the exact opposite of remaining" because `remaining()` tells you `executionTimestamp - currentTimestamp`, so the exact opposite of that would be `currentTimestamp - executionTimestamp`, but that's not what you're looking for. You need to know `currentTimestamp - startTimestamp`, which makes sense.

**Comment by emahuni** [comment]
Ohhh okay, yah, makes sense, I think you got it.

**Comment by rommelsantor** [comment]
@emahuni Added in v2.7.0. Thanks!
